version: '3.8'

services:
  # Base de datos H2 (para desarrollo/producción simple)
  h2-database:
    image: oscarfonts/h2
    container_name: skinslabs-h2
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      H2_OPTIONS: "-ifNotExists"
    volumes:
      - h2-data:/h2-data
    networks:
      - skinslabs-network

  # Aplicación Spring Boot
  skinslabs-backend:
    build: .
    container_name: skinslabs-backend
    ports:
      - "8181:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2-database:9092/skinslabsdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - JAVA_OPTS=-Xmx512m -Xms256m
    volumes:
      - uploads-data:/app/uploads
    depends_on:
      - h2-database
    networks:
      - skinslabs-network
    restart: unless-stopped

  # Nginx como proxy reverso (opcional)
  nginx:
    image: nginx:alpine
    container_name: skinslabs-nginx
    ports:
      - "8090:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - skinslabs-backend
    networks:
      - skinslabs-network
    restart: unless-stopped

volumes:
  h2-data:
    driver: local
  uploads-data:
    driver: local

networks:
  skinslabs-network:
    driver: bridge 